Add display of electronic portfolio links for Alma documents
pulibrary/orangelight pull request #2370
Opened 2021-03-12 21:44 UTC by eliotjordan

Works toward #2273 

Adds a new fields to hold electronic portfolio objects from the 951 or AVA fields in Alma records. The links and labels in the field are displayed in the "Available Online" section of the show page and replace the data retrieved from Umlaut.

- New field `electronic_portfolio_s' is multi-valued and holds an escaped JSON strings. Similar to `electronic_access_1display`
- The JSON has the following format:
  ```
    {
      "desc": "Available from 1869 volume: 1 issue: 1.",
      "title": "Nature",
      "url": "https://na07.alma.exlibrisgroup.com/view/uresolver/01PRI_INST/openurl?u.ignore_date_coverage=true&amp;portfolio_pid=53443322610006421&amp;Force_direct=true",
      "start": "1869",
      "end": "latest"
    }
  ```

2021-03-12 23:53 UTC, kevinreiss commented
That JSON looks on target to me.

2021-03-15 16:10 UTC, christinach requested changes
@eliotjordan , @mzelesky and I have reviewed the PR and the related issues about electronic records. The PR looks ok but it would be good to also include a fixture that has an embargo (where there is a 954 field in the publishing record). 

This issue https://github.com/pulibrary/bibdata/issues/1001 describes in depth the electronic record and how we would calculate the embargo in bibdata.
 
We will calculate the start and end years in bibdata but it would good to also include in this PR the example mms_id: 99122412208706421 from this issue https://github.com/pulibrary/bibdata/issues/1001. Using the above mms_id the year range would say 1880-latest without the embargo accounted for. But with the embargo it would say 1880-2015 (current example from catalog: https://catalog.princeton.edu/catalog/857469 Science with embargo).

2021-03-16 17:05 UTC, hackartisan requested changes
Looks great; 2 small things

2021-03-17 15:27 UTC, eliotjordan commented on app/models/solr_document.rb
> +  def sibling_documents
Fixed

2021-03-17 15:27 UTC, eliotjordan commented on spec/features/availability_spec.rb
> +        expect(page).to have_text ' Available from 1869 volume: 1 issue: 1.'
removed

2021-03-17 17:37 UTC, hackartisan approved these changes

2021-03-17 19:03 UTC, eliotjordan commented
@christinach I added some fixture data and a test to show how embargoed dates are displayed. However, the logic that calculates the embargoed date is in bibdata.

2021-03-18 01:51 UTC, christinach approved these changes

2021-03-18 01:51 UTC, christinach commented on spec/features/availability_spec.rb
> +
This is ok based on the published fixture in bibdata 
`<datafield tag="954" ind1="" ind2="">
    <subfield code="a">53443322630006421</subfield>
    <subfield code="b">&gt;=</subfield>
    <subfield code="c">1</subfield>
  </datafield>`

I will approve this PR based on the display. 
We need though to improve the calculation for the emabrgo date. I opened issue https://github.com/pulibrary/bibdata/issues/1147 with more information on the embargo date. 
Thank you !

2021-03-18 16:21 UTC, merged