Availability for bib records with temporary locations
pulibrary/orangelight pull request #2465
Opened 2021-05-20 18:58 UTC by hectorcorrea

Adds a check to make a second availability call to bib data when the initial call reports temporary locations. This is required because Alma does not provide holding information when items are in temporary locations. 

The new code looks to see if Alma reported temporary locations, if it did, then it makes a second availability call to bib data but this time explicitly request to fetch the holding information (via the deep=true query string parameter). This second call is slow and therefore we only make it when we detect temporary locations.

When there are no temporary locations in the initial call to bib data we use the data that we got in the first call. 

This is a good record to test since it has temporary locations: `9959958323506421`

2021-05-20 18:59 UTC, hectorcorrea commented on app/javascript/orangelight/availability.es6
> +      this.update_single(holding_records);
Uses data from the first call to bib data. This is good as-is.

2021-05-20 18:59 UTC, hectorcorrea commented on app/javascript/orangelight/availability.es6
> +    $.getJSON(url, this.update_single)
Makes second call to bib data and uses the result of this call to update the page.

2021-05-20 19:42 UTC, hectorcorrea commented on app/javascript/orangelight/availability.es6
> +    $.getJSON(url, this.update_single)
The incomplete data looks like this (notice the `fake_id`):

```
{
    "9959958323506421": {
        "fake_id_1": {
            "on_reserve": "N",
            "location": "lewis$resterm",
            "label": "Lewis Library: Term Loan Reserves",
            "status_label": "Available",
            "copy_number": null,
            "cdl": false,
            "temp_location": true,
            "id": "fake_id_1"
        }
    }
}
```

The second call will give the return the proper data (notice the correct holding_ids):
```
{
    "9959958323506421": {
        "22272063570006421": {
            "on_reserve": "N",
            "location": "lewis$resterm",
            "label": "sciresp: Lewis: Term Loan",
            "status_label": "Available",
            "copy_number": "1",
            "cdl": false,
            "temp_location": true,
            "id": "22272063570006421"
        },
        "22272063520006421": {
            "on_reserve": "N",
            "location": "lewis$resterm",
            "label": "sciresp: Lewis: Term Loan",
            "status_label": "Available",
            "copy_number": "2",
            "cdl": false,
            "temp_location": true,
            "id": "22272063520006421"
        }
    }
}
```

2021-05-20 20:04 UTC, hackartisan requested changes
It would be great to get a test for this in spec/javascript/orangelight/availability.spec.js

2021-05-21 19:47 UTC, hectorcorrea commented
Added unit test.

2021-05-21 20:29 UTC, hackartisan approved these changes

2021-05-21 20:29 UTC, merged