Availability for records in temporary locations
pulibrary/orangelight pull request #2527
Opened 2021-06-22 19:15 UTC by hectorcorrea

Use 'Check record' as the label for records in temp locations since otherwise they stay with the 'Loading...' label. Notice that we cannot determine the availability for these records because Alma does not return it to us on the normal bib level API call. In the show page we make a second (and slow-ish) API call to fetch the complete information and hence the hint to "Check Record" to allow the user to view all the information if they are indeed interested in this record.

Fixes #2524

![temp_location_av](https://user-images.githubusercontent.com/568286/122985548-53282280-d36c-11eb-9c82-81f1af0ff869.png)

2021-06-22 19:17 UTC, hectorcorrea commented on app/javascript/orangelight/availability.es6
> +      if (availability_info['temp_location']) {
This is unrelated to this PR and the `if` block is probably not even needed anymore, but at least now it uses the correct property name (`temp_location`)

2021-06-22 21:05 UTC, hackartisan requested changes
Thank you for including the screen shot. When I looked at it, my first thought was "check record for what?" since it's the first result and I didn't have the context of "Available" or "Not Available" to slot the new value into. I wonder if it should say "Check record for Availability"?

Also you know I am going to ask! How feasible would it be to add a test for this change?

2021-06-23 16:59 UTC, hectorcorrea commented
@hackartisan I changed the label (see picture below) and added a test for it.

![temp_location_av](https://user-images.githubusercontent.com/568286/123138180-beccc700-d422-11eb-8107-4d9caa329535.png)

2021-06-23 17:55 UTC, hackartisan approved these changes
Great, thanks!

2021-06-23 17:55 UTC, merged