Caches the Solr data for the home page
pulibrary/orangelight pull request #2650
Opened 2021-08-11 20:50 UTC by hectorcorrea

Fixes #2637

2021-08-11 20:52 UTC, hectorcorrea commented on app/controllers/catalog_controller.rb
> +      params.keys.count == 2
We could tweak this logic to make sure that neither `q` nor `f` (facet) are present. But as-is it should catch the vast majority of calls.

2021-08-11 20:58 UTC, hectorcorrea commented on spec/controllers/catalog_controller_spec.rb
> +      expect(controller).to have_received(:render_empty_search)
I am only testing that the `render_empty_search` method was called in the Controller but not the logic inside of it nor the code inside `empty_solr_response` and `empty_raw_response`. Let me know if you think we should test deeper.

2021-08-12 13:01 UTC, hackartisan requested changes
This looks good to me but rspec is saying the test needs mocks or spies and I don't think you want to mock the controller under test. I wonder if a mock of the Rails cache would work, and then you could test that it calls fetch. And/or a test that that logger message is written?

2021-08-12 15:00 UTC, hectorcorrea commented
@hackartisan I fixed the tests and now they pass (sorry about that!) and in addition they now check whether the Rails cache was used which is a better test for this scenario.

2021-08-12 16:13 UTC, christinach approved these changes

2021-08-12 16:16 UTC, merged