Fix constraint display when facets applied in certain order
pulibrary/orangelight pull request #2884
Opened 2022-03-02 16:43 UTC by sandbergja

closes #2874

2022-03-02 18:53 UTC, carolyncole requested changes
Nice work tracking down a quick fix.  I had a couple comments on the changes.  If making these updates does not make sense because this is not the final code just let me know.

2022-03-02 18:53 UTC, carolyncole commented on app/helpers/application_helper.rb
> +      value.map { |v| render_location_code(v) }
@sandbergja Recursion is a bit complex in this situation.  I might have just cast the single value to an Array with 
```
Array(value).map do |loc|
   location = Bibdata.holding_locations[loc.to_sym]
   location.nil? ? value : "#{value}: #{location_full_display(location)}"
end
```

2022-03-02 18:53 UTC, carolyncole commented on spec/system/searching_spec.rb
> +
This test is great.  There is also a test for the helper, which would be a great place to add a test for the syntax of the output https://github.com/pulibrary/orangelight/blob/34bf790fd5fb9aab0cdbbd7f514ff0b5d2c39fa4/spec/helpers/locations_spec.rb#L49

2022-03-03 16:29 UTC, carolyncole approved these changes

2022-03-07 15:16 UTC, christinach approved these changes

2022-03-07 15:16 UTC, merged