Do not load catalog javascript for request pages
pulibrary/orangelight pull request #2936
Opened 2022-04-07 20:31 UTC by carolyncole

request feature tests before the change
```
Finished in 4 minutes 44 seconds (files took 7.43 seconds to load)
88 examples, 0 failures, 12 pending
```

request feature tests after the change
```
Finished in 54.36 seconds (files took 7.03 seconds to load)
88 examples, 0 failures, 12 pending
```

2022-04-07 20:54 UTC, christinach requested changes
@carolyncole even though it is reducing the test time, it is breaking the request form because  it's not loading some javascript; data tables break and dropdows are also not responsive. I tested it on staging and compared with prod. :(

2022-04-08 12:13 UTC, carolyncole commented
@christinach good catch!  I went ahead and changed things around to include a request javascript.  The requests pages seem to be working now.  Can you please test staging again and see if the issues you were seeing are resolved?  I'm still seeing a great speed change in the tests including all the style sheets, but changing around the javascript.

```
Finished in 57.11 seconds (files took 11.11 seconds to load)
88 examples, 0 failures, 12 pending
```

2022-04-08 12:57 UTC, christinach commented
@carolyncole thank you. the latest push, fixed the data table error and I can see 'search by enumeration' and no errors in the console. I was testing 'Nature' . https://catalog-staging.princeton.edu/requests/994264203506421?mfhd=22697858020006421. 
Also the rest of the dropdowns in the navbar work again. We are good!

2022-04-08 12:58 UTC, christinach approved these changes

2022-04-08 12:58 UTC, merged