Request form - retrieve items for resource sharing
pulibrary/orangelight pull request #3032
Opened 2022-06-03 00:40 UTC by christinach

closes #3002 
In the request form, retrieve items for resource sharing location, `RES_SHARE$IN_RS_REQ`

2022-06-03 00:50 UTC, christinach commented
see https://catalog-qa.princeton.edu/requests/9991807103506421?mfhd=22696270550006421

![Screen Shot 2022-06-02 at 8 46 39 PM](https://user-images.githubusercontent.com/9905193/171763249-8467b942-1856-417c-b65e-1498716bea7b.png)

This is in https://catalog-qa.princeton.edu/ which retrieves availability from alma production. I made sure to index the record against catalog-qa so that we can see the example record. 
I haven't updated the status in JS yet but it can be done in a separate PR. 
This PR allows patrons to request the item using the request form.

2022-06-03 00:56 UTC, christinach commented
Do we want the request form to display 'Firestone Stacks' or is it ok to display 'Resource Sharing'. The record page displays 'Firestone Stacks'.

2022-06-03 12:58 UTC, maxkadel requested changes
Can we add a test for this behavior? I'm still a little confused about what the expected behavior for these items is, and that might help clarify them.

2022-06-03 13:10 UTC, mzelesky commented
I would think we'd want the request form to display the same thing as the record page.

2022-06-03 13:16 UTC, christinach commented
> 

@maxkadel I didnt open the PR for review because there was no test. I have added one now and will open it for review.

2022-06-03 13:27 UTC, christinach commented
> I would think we'd want the request form to display the same thing as the record page.

Will do @mzelesky thanks for checking the screenshot

2022-06-03 15:23 UTC, christinach commented
I've update the location display in the request form per @mzelesky request:

![Screen Shot 2022-06-03 at 11 22 57 AM](https://user-images.githubusercontent.com/9905193/171883938-c141081f-1d30-4c62-9e79-08c60acc0923.png)

2022-06-03 16:28 UTC, christinach commented
This PR will allow patrons to request items from resource sharing. 
@carolyncole @maxkadel a heads up that availability is failing in this record which means: no status in the record page and the location we are seeing (Firestone Library - Stacks ) even though it's the desired one, it displays because it's the fall back look up to [Bibdata](https://bibdata.princeton.edu/locations/holding_locations.json) when the Js availability response is failing. 

I will work on a separate PR to update availability status and make sure that the location display is the permanent location.

2022-06-06 16:00 UTC, maxkadel approved these changes

2022-06-06 16:30 UTC, carolyncole requested changes
@christinach Just one question

2022-06-06 16:30 UTC, carolyncole commented on app/models/requests/request.rb
> +        calculate_holding = if item["in_temp_library"] && item["temp_location_code"] != "RES_SHARE$IN_RS_REQ"
Can this utilize the helper method? `.in_resource_sharing?`

2022-06-06 20:05 UTC, carolyncole approved these changes

2022-06-06 20:05 UTC, merged