Adds vocabulary column to subject table
pulibrary/orangelight pull request #3386
Opened 2023-01-27 23:38 UTC by christinach

closes https://github.com/pulibrary/orangelight/issues/1982

update multiple genre vocab
Update the browse_facet task to check for subject facet update browselists load_facet to look for subject facet Include fixtures
Updates subjects.sorted

2023-01-30 15:30 UTC, christinach commented
@mzelesky and I reviewed the search results of this PR. It seems to be a little bit more complicated and we should discuss this in the Orangelight meeting on 2/9/2023.

2023-02-16 18:59 UTC, christinach commented
> @mzelesky and I reviewed the search results of this PR. It seems to be a little bit more complicated and we should discuss this in the Orangelight meeting on 2/9/2023.

In the OL/Bibdata meeting we discussed that we need to support browselists with the additional subject and vocabulary searches that we've added in the recent years.

2024-09-23 16:56 UTC, christinach commented
@christinach when I update this PR put back the .sorted

2025-03-06 22:06 UTC, christinach commented
@mzelesky and I reviewed this again. We want to create Browse and Search links on the record page in the section 'Details' for the different vocabularies we index:
[homoit_genre_s](https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/traject_config.rb#L941)
[lcgft_s](https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/traject_config.rb#L946)
[aat_s](https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/traject_config.rb#L951)
[rbgenr_s](https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/traject_config.rb#L956)
[siku_subject_display](https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/traject_config.rb#L890C11-L890C31)
[local_subject_display](https://github.com/pulibrary/bibdata/blob/main/marc_to_solr/lib/traject_config.rb#L895)

Create a new `subject_lc` field that will be used for the browse and Search link and will only include: 
   ```
   subjects = process_hierarchy(record, 
'600|*0|abcdfklmnopqrtvxyz:610|*0|abfklmnoprstvxyz:611|*0|abcdefgklnpqstvxyz:630|*0|adfgklmn oprstvxyz:650|*0|abcvxyz:651|*0|avxyz')
  subjects = augment_the_subject.add_indigenous_studies(subjects)
  subjects = ChangeTheSubject.fix(subject_terms: subjects)
```

2025-03-18 17:51 UTC, christinach commented
Subject browse issue: when the user is in the record page and clicks on browse link, highlight the targeted term and vocabulary in the subject browse page. Right now if there are two same terms it highlights the one on the top regardless of the vocabulary.

2025-03-18 19:58 UTC, christinach commented
We reviewed the vocabulary feature with Cathy and our team. 
The branch is deployed and reindexed on [catalog-qa.princeton.edu](https://catalog-qa.princeton.edu/). 
 Cathy will bring this to the authority control group for further feedback on Thursday 3/18/2025.

We need to address: https://github.com/pulibrary/orangelight/pull/3386#issuecomment-2734213468
We're waiting for feedback regarding same terms in subject browse when they belong to different vocabularies. 1. Do we want to order them based on the number of records they have? 2. Can we leave it as it is and have the user driven only by the vocabulary? 3. Do we agree with the vocabulary and the wording in subject browse?

2025-03-27 21:48 UTC, christinach commented
There are some tests that I'd like to add and update. I will do this on Monday 3/31/2025. 🐬

2025-04-01 00:53 UTC, sandbergja requested changes
This is so nice!  Thanks, @christinach 🐬 -- I just noticed a few very small things.  The one in the catalog controller is the only thing that I think needs to be fixed before merging.

2025-04-01 00:53 UTC, sandbergja commented on app/components/orangelight/process_vocabulary_component.rb
> +  private_constant :SEPARATOR, :QUERYSEP, :FACET_KEYS
👍🏻

2025-04-01 00:53 UTC, sandbergja commented on app/controllers/catalog_controller.rb
> +    config.add_show_field 'cumulative_index_finding_aid_display', label: 'Cumulative index/\u200BFinding aid'
```suggestion
    config.add_show_field 'cumulative_index_finding_aid_display', label: "Cumulative index/\u200BFinding aid"
```

Shouldn't we keep this with double quotes, so it doesn't display `\u200B` literally?

2025-04-01 00:53 UTC, sandbergja commented on app/controllers/orangelight/browsables_controller.rb
> +                      end
👍🏻

2025-04-01 00:53 UTC, sandbergja commented on app/controllers/orangelight/browsables_controller.rb
> +      @model == 'subjects' ? @match_vocabulary = search_result.vocabulary : nil
Is this the same as?
```suggestion
      @match_vocabulary = search_result.vocabulary if @model == 'subjects'
```

2025-04-01 00:53 UTC, sandbergja commented on app/views/orangelight/browsables/index.html.erb
> +<%  %>
Can we remove this line?

2025-04-01 13:43 UTC, sandbergja approved these changes
Thanks, @christinach ! 🐬 Let's merge this! 🎉

2025-04-01 13:44 UTC, merged