Use Atkinson Hyperlegible Font
pulibrary/orangelight pull request #3958
Opened 2024-02-06 22:04 UTC by christinach

closes #3677

2024-02-06 22:06 UTC, sandbergja requested changes

2024-02-06 22:06 UTC, sandbergja commented on app/assets/stylesheets/variables/typography.scss
> +$font-sans: 'Atkinson Hyperlegible','Times New Roman', sans-serif !default;
```suggestion
$font-sans: 'Atkinson Hyperlegible','Dejavu Sans', Helvetica, sans-serif !default;
```

Could we keep the same font fallback options for non-Latin characters?

2024-04-01 15:43 UTC, sandbergja approved these changes
Thanks, @christinach ! 🐬

2024-04-02 15:08 UTC, christinach commented
This is [an example record](https://catalog.princeton.edu/catalog/9947668823506421) that was reported [for the font in the call number](https://github.com/pulibrary/orangelight/issues/3275) . It looks very clear with the Atkinson font.

2024-04-02 15:15 UTC, merged