Add MLA citation for SCSB items
pulibrary/orangelight pull request #4427
Opened 2024-10-08 13:09 UTC by maxkadel

2024-10-09 07:22 UTC, maxkadel commented on app/components/orangelight/document/citation_component.rb
> +    'blacklight.citation.mla': :export_as_mla,
Ticket to route all types of records through the same routines - https://github.com/pulibrary/orangelight/issues/4428

2024-10-09 16:09 UTC, sandbergja requested changes
Thanks, @maxkadel !  🦄  I saw one very small thing in the Gemfile, the actual code looks great to me.

2024-10-09 16:09 UTC, sandbergja commented on spec/models/apa_spec.rb
> +RSpec.describe Blacklight::Document::Apa, citation: true do
Woohoo citation tag!

2024-10-09 16:09 UTC, sandbergja commented on app/models/concerns/blacklight/document/apa.rb
> +module Blacklight::Document::Apa
I like this structure with the 3 modules for the 3 citation styles

2024-10-10 12:38 UTC, sandbergja approved these changes
Woohoo!  Thanks, @maxkadel 🦄

2024-10-10 15:09 UTC, merged